Update opr_jfile_8363488A

diff --git a/opr_jfile_8363488A b/opr_jfile_8363488A
--- a/opr_jfile_8363488A
+++ b/opr_jfile_8363488A
@@ -9,56 +9,71 @@ pipeline {
             }
         }
 
+        // =========================
+        // STAGE 2
+        // =========================
         stage('stg2-8363488A') {
             steps {
                 script {
-                    sh """
-                    curl -Is http://localhost:8081 | head -n 1 > /tmp/testsvr-result-file
-                    """
+
+                    sh 'curl -Is http://localhost:8081 | head -n 1 > /tmp/testsvr-result-file'
 
                     def result = sh(
-                        script: "cat /tmp/testsvr-result-file",
+                        script: 'cat /tmp/testsvr-result-file',
                         returnStdout: true
                     ).trim()
 
-                    if (result.contains("200")) {
-                        echo "stg2_8363488A: testsvr’s website is running"
-
-                        input message: "Proceed to update testsvr server?"
-
+                    if (result.contains('200')) {
+                        echo 'stg2_8363488A: testsvr’s website is running'
+                        input message: 'Proceed to update testsvr server?'
                     } else {
-                        echo "stg2_8363488A: testsvr’s website is down"
-                        error("Aborting pipeline because testsvr is down.")
+                        echo 'stg2_8363488A: testsvr’s website is down'
+                        error('Aborting pipeline because testsvr is down.')
                     }
-                }            }
-        }
-
-        stage('stg3-8363488A') {
-            steps {
-                echo 'stg3-8363488A: testsvr is backup and updated'
+                }
             }
         }
 
+        // =========================
+        // STAGE 3
+        // =========================
+        stage('stg3-8363488A') {
+            steps {
+                script {
+
+                    sh 'docker image rm testsvr_image || true'
+                    sh 'docker commit testsvr_8363488A testsvr_image'
+
+                    sh 'bolt script run opr_script_8363488A --targets testsvr_8363488A'
+
+                    echo 'stg3_8363488A: testsvr is backup and updated'
+                }
+            }
+        }
+
+        // =========================
+        // STAGE 4
+        // =========================
         stage('stg4-8363488A') {
             steps {
-                    sh """
-                    curl -Is http://localhost:8081 | head -n 1 > /tmp/testsvr-result-file
-                    """
+                script {
+
+                    sh 'curl -Is http://localhost:8081 | head -n 1 > /tmp/testsvr-result-file'
 
                     def result = sh(
-                        script: "cat /tmp/testsvr-result-file",
+                        script: 'cat /tmp/testsvr-result-file',
                         returnStdout: true
                     ).trim()
 
-                    if (result.contains("200")) {
-                        echo "stg4_8363488A: testsvr’s website is running after update"
-
-                        input message: "Proceed to update appsvr server?"
-
+                    if (result.contains('200')) {
+                        echo 'stg4_8363488A: testsvr’s website is running after update'
+                        input message: 'Proceed to update appsvr server?'
                     } else {
-                        echo "stg4_8363488A: testsvr’s website is down"
-                        error("Aborting pipeline because updated testsvr is down.")
-                    }            }
+                        echo 'stg4_8363488A: testsvr’s website is down'
+                        error('Aborting pipeline because updated testsvr is down.')
+                    }
+                }
+            }
         }
 
         stage('stg5-8363488A') {
@@ -72,6 +87,5 @@ pipeline {
                 echo 'Stage 6 running...'
             }
         }
-
     }
 }
